AWSTemplateFormatVersion: "2010-09-09"
Description: ASG task using Cloudformation

Resources:
  Debian:
    Type: AWS::EC2::Instance
    Properties:
      LaunchTemplate:
        LaunchTemplateName: DebianLT
        Version: 1
