AWSTemplateFormatVersion: "2010-09-09"
Description: ASG task using Cloudformation

Resources:
  Debian:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-07d02ee1eeb0c996c
      InstanceType: t2.micro
      