AWSTemplateFormatVersion: "2010-09-09"
Description: ASG task using Cloudformation

Resources:
  myLaunchConfig:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      ImageId: ami-07d02ee1eeb0c996c
      InstanceType: t2.micro
      KeyName: TestKey

  myASG:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      AvailabilityZones: 
        - us-east-1a
        - us-east-1b
        - us-east-1c
      MaxSize: "1"
      MinSize: "1"
      DesiredCapacity: "1"
      LaunchConfigurationName: !Ref myLaunchConfig

