AWSTemplateFormatVersion: "2010-09-09"
Description: ASG task using Cloudformation

Resources:
  Debian:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-07d02ee1eeb0c996c
      InstanceType: t2.micro

  myLaunchConfig:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      ImageId: ami-07d02ee1eeb0c996c
      InstanceType: t2.micro
      

  myASG:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      AutoScalingGroupName: LHmyASG
      AvailabilityZones: 
        - us-east-1a
        - us-east-1b
        - us-east-1c
      MaxSize: "1"
      MinSize: "0"
      DesiredCapacity: "1"
      LaunchConfigurationName: !Ref myLaunchConfig

