AWSTemplateFormatVersion: "2010-09-09"
Description: ASG task using Cloudformation

Resources:
  Debian:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-07d02ee1eeb0c996c
      InstanceType: t2.small


  myLaunchConfig:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      ImageId: ami-07d02ee1eeb0c996c
      InstanceType: t2.small


  myASG:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      AvailabilityZones: 
        - us-east-1a
        - us-east-1b
        - us-east-1c
      LaunchConfigurationName: !Ref myLaunchConfig
      MaxSize: "1"
      MinSize: "1"
      DesiredCapacity: "1"
<<<<<<< HEAD
    UpdatePolicy:
      AutoscalingReplacingUpdate:
        WillReplace: 'true'
=======
>>>>>>> 114a3c39ff9903592735194b978264549d622443
