AWSTemplateFormatVersion: "2010-09-09"

Resources:
  Debian:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-07d02ee1eeb0c996c
      InstanceType: t2.micro

  myLaunchConfig: 
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      ImageId: ami-07d02ee1eeb0c996c
      InstanceType:  t2.small

  myASG:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      MinSize: 1
      MaxSize: 1
      DesiredCapacity: 1
      AvailabilityZones:
        - us-east-1a
        - us-east-1b
        - us-east-1c
      LaunchConfigurationName: !Ref myLaunchConfig
    UpdatePolicy:
      AutoScalingReplacingUpdate:
        WillReplace: 'true'
