AWSTemplateFormatVersion: "2010-09-09"
Description: ASG task using Cloudformation

Resources:
  DebianLT:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName: MyDebianInstance
      LaunchTemplateData:
        ImageId: ami-07d02ee1eeb0c996c
        InstanceType: t2.small
        BlockDeviceMappings:
          - Ebs:
              VolumeSize: 8
              VolumeType: gp2
              DeleteOnTermination: true
              Encrypted: true
            DeviceName: /dev/sda
        KeyName: myec2kp

  # myLaunchConfig:
  #   Type: AWS::AutoScaling::LaunchConfiguration
  #   Properties:
  #     ImageId: ami-07d02ee1eeb0c996c
  #     InstanceType: t2.small
  #     KeyName: myec2kp
  #     BlockDeviceMappings:
  #     - DeviceName: /dev/sda
  #       VirtualName: ephemeral0

  
  myASG:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      AutoScalingGroupName: LHmyASG
      AvailabilityZones: 
        Fn::GetAZs: us-east-1
      LaunchTemplate:
        LaunchTemplateName: DebianLT
      MaxSize: "1"
      MinSize: "1"
      DesiredCapacity: "1"
      Tags:
        - Key: Environment
          Value: Production
          PropagateAtLaunch: "True"
    UpdatePolicy:
      AutoScalingReplacingUpdate:
        WillReplace: "True"  