AWSTemplateFormatVersion: "2010-09-09"
Description: ASG task using Cloudformation

Resources:
  myLaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName: myLaunchTemplate
      LaunchTemplateData:
        ImageId: ami-07d02ee1eeb0c996c
        InstanceType: t2.medium
        KeyName: TestKey

  myASG:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      AvailabilityZones: 
        - us-east-1a
        - us-east-1b
        - us-east-1c
      LaunchTemplate:
        LaunchTemplateId: !Ref myLaunchTemplate
        Version: "1"
      MaxSize: "1"
      MinSize: "0"
      DesiredCapacity: "1"
    UpdatePolicy:
      AutoScalingReplacingUpdate:
        WillReplace: "true"  