AWSTemplateFormatVersion: "2010-09-09"

Resources:
  Debian:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-07d02ee1eeb0c996c
      InstanceType: t2.micro

  myLaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties: 
      LaunchTemplateData: 
        ImageId: ami-07d02ee1eeb0c996c
        InstanceType: t2.micro

  myASG:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      MinSize: 1
      MaxSize: 2
      DesiredCapacity: 2
      AvailabilityZones:
        - us-east-1a
        - us-east-1b
        - us-east-1c
      LaunchTemplate:
        LaunchTemplateId: !Ref myLaunchTemplate
        Version: 1
    UpdatePolicy:
      AutoScalingReplacingUpdate:
        WillReplace: 'true'
