AWSTemplateFormatVersion: "2010-09-09"
Description: EC2 task using Cloudformation

Resources:
  Windows:
    Type: AWS::EC2::Instance
    Properties:
      LaunchTemplate:
        LaunchTemplateName: WindowsServer
        Version: 2
  Ubuntu:
    Type: AWS::EC2::Instance
    Properties:
      LaunchTemplate:
        LaunchTemplateName: UbuntuServer
        Version: 1
