AWSTemplateFormatVersion: "2010-09-09"
Description: EC2 task using Cloudformation

Resources:
  Ubuntu:
    Type: AWS::EC2::Instance
    Properties:
      LaunchTemplate:
        LaunchTemplateName: UbuntuServer
        Version: 1
  
  MyEIP:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc
      InstanceId: !Ref Ubuntu

Outputs:
  PublicIP:
    Value: !GetAtt Ubuntu.PublicIp