AWSTemplateFormatVersion: '2010-09-09'
Description: Laeticia's Test Stack

Parameters:
  AMI:
    Type: String
  InstanceType:
    Type: String
  KeyFile:
    Type: String
  Username:
    Type: String

Resources:
  EC2Instance:
    Type: "AWS::EC2::Instance"
    Properties:
      ImageId: !Ref AMI
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyFile
      SubnetId: !ImportValue vpctask-Subnet
      SecurityGroupIds:
        - Ref: InstanceSecurityGroup

  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
        GroupDescription: Allow ssh/ICMP
        VpcId: !ImportValue vpctask-VPC
        SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: icmp
          FromPort: 8
          ToPort: -1
          CidrIp: 0.0.0.0/0
Outputs:
  InstanceID:
    Value: !Ref EC2Instance
  PrivateIP:
    Value: !GetAtt EC2Instance.PrivateIp