AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  AMI:
    Type: String
  InstanceType:
    Type: String
  KeyFile:
    Type: String
  Username:
    Type: String

Resources:
  EC2Instance:
    Type: "AWS::EC2::Instance"
    Properties:
      ImageId: !Ref AMI
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyFile
      SubnetId: !ImportValue vpctask-mypubSubnet
      SecurityGroupIds:
        - Ref: InstanceSecurityGroup

  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
        GroupDescription: Allow ssh/ICMP
        VpcId: !ImportValue vpcstack-VPC
        SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: icmp
          FromPort: 8
          ToPort: -1
          CidrIp: 0.0.0.0/0
  MyEIP:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc
      InstanceId: !Ref EC2Instance

Outputs:
  PublicIP:
    Value: !GetAtt EC2Instance.PublicIp  
  MyEIPAllocationId:
    Value: !Ref MyEIP
    Export:
      Name: !Sub "${AWS::StackName}-AllocationId"
