AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  AMI:
    Type: String
  InstanceType:
    Type: String
  KeyFile:
    Type: String
  Username:
    Type: String

Resources:
  PubNacl:
    Type: "AWS::EC2::NetworkAcl"
    Properties:
      VpcId:  !ImportValue vpctask-VPC
  
  PubInbound:
    Type: AWS::EC2:NetworkAclEntry
    Properties:
      NetworkAclId: !Ref PubNaclId
      RuleNumber: 100
      Protocol: tcp
      RuleAction: allow
      Egress: "true"
      CidrBlock: 0.0.0.0/0
      PortRange:
        From: 22
        To: 22

  PubOutbound:
    Type: AWS::EC2:NetworkAclEntry
    Properties:
      NetworkAclId: !Ref PubNaclId
      RuleNumber: 500
      Protocol: tcp
      RuleAction: allow
      Egress: "true"
      CidrBlock: 0.0.0.0/0
      PortRange:
        From: 80
        To: 80 