AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  checkParameterExists:
    Type: AWS::SSM::Parameter::Name
  VPC:
    Type: AWS::EC2::VPC::Id
  PublicSubnet1:
    Type: AWS::EC2::Subnet::Id
  PublicSubnet2:
    Type: AWS::EC2::Subnet::Id
  PublicSubnet3:
    Type: AWS::EC2::Subnet::Id
  myName:
    Type: AWS::SSM::Parameter::Value<String>
  myTitle:
    Type: AWS::SSM::Parameter::Value<String>
  myStartdate:
    Type: AWS::SSM::Parameter::Value<String>
  myHomestate:
    Type: AWS::SSM::Parameter::Value<String>
  myAddress:
    Type: AWS::SSM::Parameter::Value<String>
  myTimezone:
    Type: AWS::SSM::Parameter::Value<String>
  myTeam:
    Type: AWS::SSM::Parameter::Value<String>

Resources:
  WebserverSG:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: "security group for EC2"
      SecurityGroupIngress: 
        - IpProtocol: "tcp"
          FromPort: 80
          ToPort: 80
          CidrIp: "0.0.0.0/0"
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: "0.0.0.0/0"

  WebServersLC:
    Type: 'AWS::AutoScaling::LaunchConfiguration'
    Properties:
      ImageId: 'ami-01cc34ab2709337aa'
      InstanceType: 't2.micro'
      KeyName: myec2kp
      SecurityGroups:
        - !Ref 'WebserverSG'
      UserData: 
        Fn::Base64:
          Fn::Sub: |
              #!/bin/bash -xe
              sudo amazon-linux-extras install -y nginx1
              sudo service nginx start
              sudo echo "<p>Hi! I'm ${myName}. I am a ${myTitle} and as of ${myStartdate} I have been working with the ${myTeam} team.<br> My address is ${myAddress} in the beautiful state of ${myHomestate} which is in the ${myTimezone} time zone.<br></p>" > /usr/share/nginx/html/index.html

  WebServerAsg:
    Type: 'AWS::AutoScaling::AutoScalingGroup'
    Properties:
      AvailabilityZones:
        - us-east-1a
        - us-east-1b
        - us-east-1c
      DesiredCapacity: 1
      HealthCheckType: 'ELB'
      HealthCheckGracePeriod: 30 
      LaunchConfigurationName: !Ref WebServersLC
      MaxSize: 2
      MinSize: 1
      TargetGroupARNs:
        - !Ref ELBTargetGroup

  ELBSG:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: "security group for ALB"
      SecurityGroupIngress: 
        - IpProtocol: "tcp"
          FromPort: 80
          ToPort: 80
          CidrIp: "0.0.0.0/0"

  ELBTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      TargetType: instance
      Port: 80
      Protocol: HTTP
      HealthCheckPath: "/index.html"
      HealthCheckPort: "traffic-port"
      HealthCheckProtocol: "HTTP"
      HealthCheckIntervalSeconds: 20
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 2
      UnhealthyThresholdCount: 3
      Matcher: 
          HttpCode: "200"
      HealthCheckEnabled: true
      VpcId: !Ref VPC
      TargetGroupAttributes: 
        - Key: "deregistration_delay.timeout_seconds"
          Value: "20"

  ApplicationLoadBalancer:
    Type: "AWS::ElasticLoadBalancingV2::LoadBalancer"
    Properties:
      Name: "My-Application-Load-Balancer"
      Scheme: "internet-facing"
      Type: "application"
      SecurityGroups:
        - !GetAtt ELBSG.GroupId
      Subnets:
        - !Ref PublicSubnet1
        - !Ref PublicSubnet2
        - !Ref PublicSubnet3
      IpAddressType: "ipv4"

  HTTPListener:
    Type: "AWS::ElasticLoadBalancingV2::Listener"
    Properties:
      LoadBalancerArn: !Ref ApplicationLoadBalancer
      Port: 80
      Protocol: "HTTP"
      DefaultActions: 
        - Order: 1
          TargetGroupArn: !Ref ELBTargetGroup
          Type: "forward"

Outputs:
    URL:
        Description: URL of the website
        Value:
            'Fn::Join':
                - ''
                - 
                    - 'http://'
                    - 
                        'Fn::GetAtt':
                            - ApplicationLoadBalancer
                            - DNSName